TOP_FAVORITE_TREES = [
    {"rank": 1, "tree": "oak"},
    {"rank": 2, "tree": "maple"},
    {"rank": 3, "tree": "pine"},
    {"rank": 4, "tree": "willow"},
    {"rank": 5, "tree": "birch"},
    {"rank": 6, "tree": "cedar"},
    {"rank": 7, "tree": "cherry"},
    {"rank": 8, "tree": "sequoia"},
    {"rank": 9, "tree": "redwood"},
    {"rank": 10, "tree": "spruce"},
    {"rank": 11, "tree": "fir"},
    {"rank": 12, "tree": "elm"},
    {"rank": 13, "tree": "ash"},
    {"rank": 14, "tree": "beech"},
    {"rank": 15, "tree": "poplar"},
    {"rank": 16, "tree": "aspen"},
    {"rank": 17, "tree": "cypress"},
    {"rank": 18, "tree": "sycamore"},
    {"rank": 19, "tree": "magnolia"},
    {"rank": 20, "tree": "dogwood"},
    {"rank": 21, "tree": "walnut"},
    {"rank": 22, "tree": "hickory"},
    {"rank": 23, "tree": "eucalyptus"},
    {"rank": 24, "tree": "baobab"},
    {"rank": 25, "tree": "palm"},
    {"rank": 26, "tree": "olive"},
    {"rank": 27, "tree": "apple"},
    {"rank": 28, "tree": "pear"},
    {"rank": 29, "tree": "plum"},
    {"rank": 30, "tree": "chestnut"},
    {"rank": 31, "tree": "hemlock"},
    {"rank": 32, "tree": "larch"},
]

TOP_FAVORITE_TREE_NAMES = [tree["tree"] for tree in TOP_FAVORITE_TREES]
